name: kigo_symfony
recipe: symfony
config:
  php: '8.2'
  via: nginx
  webroot: public
services:
  database:
    type: mysql
    portforward: 3308
    creds:
      user: kigouser
      password: kigo2024
      database: kigodata
  node:
    type: node:18
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node
